
module.exports = {
	
	'IMT01': 'RUSSIA-SAUDI ARABIA, Moscow, 14 June',
	'IMT02': 'EGYPT-URUGUAY, Ekaterinburg, 15 June',
	'IMT03': 'PORTUGAL-SPAIN, Sochi, 15 June',
	'IMT04': 'MAROCCO-IRAN, Saint Petersburg, 15 June',
	'IMT05': 'FRANCE-AUSTRALIA, Kazan, 16 June',
	'IMT06': 'PERU-DENMARK, Saransk, 16 June',
	'IMT07': 'ARGENTINA-ICELAND, Moscow, 16 June',
	'IMT08': 'CROATIA-NIGERIA, Kaliningrad, 16 June',
	'IMT09': 'BRAZIL-SWITZERLAND, Rostov-on-Don, 17 June',
	'IMT10': 'COSTA RICA-SERBIA, Samara, 17 June',
	'IMT11': 'GERMANY-MEXICO, Moscow, 17 June',
	'IMT12': 'SWEDEN-KOREA REPUBLIC, Nizhny Novgorod, 18 June',
	'IMT13': 'BELGIUM-PANAMA, Sochi, 18 June',
	'IMT14': 'TUNISIA-ENGLAND, Volgograd, 18 June',
	'IMT15': 'POLAND-SENEGAL, Moscow, 19 June',
	'IMT16': 'COLOMBIA-JAPAN, Saransk, 19 June',
	'IMT17': 'RUSSIA-EGYPT, Saint Petersburg, 19 June',
	'IMT18': 'URUGUAY-SAUDI ARABIA, Rostov-on-Don, 20 June',
	'IMT19': 'PORTUGAL-MAROCCO, Moscow, 20 June',
	'IMT20': 'IRAN-SPAIN, Kazan, 20 June',
	'IMT21': 'FRANCE-PERU, Ekaterinburg, 21 June',
	'IMT22': 'DENMARK-AUSTRALIA, Samara, 21 June',
	'IMT23': 'ARGENTINA-CROATIA, Nizhny Novgorod, 21 June',
	'IMT24': 'NIGERIA-ICELAND, Volgograd, 22 June',
	'IMT25': 'BRAZIL-COSTA RICA, Saint Petersburg, 22 June',
	'IMT26': 'SERBIA-SWITZERLAND, Kaliningrad, 22 June',
	'IMT27': 'GERMANY-SWEDEN, Sochi, 23 June',
	'IMT28': 'KOREA REPUBLIC-MEXICO, Rostov-on-Don, 23 June',
	'IMT29': 'BELGIUM-TUNISIA, Moscow, 23 June',
	'IMT30': 'ENGLAND-PANAMA, Nizhny Novgorod, 24 June',
	'IMT31': 'POLAND-COLOMBIA, Kazan, 24 June',
	'IMT32': 'JAPAN-SENEGAL, Ekaterinburg, 24 June',
	'IMT33': 'URUGUAY-RUSSIA, Samara, 25 June',
	'IMT34': 'SAUDI ARABIA-EGYPT, Volgograd, 25 June',
	'IMT35': 'IRAN-PORTUGAL, Saransk, 25 June',
	'IMT36': 'SPAIN-MAROCCO, Kaliningrad, 25 June',
	'IMT37': 'DENMARK-FRANCE, Moscow, 26 June',
	'IMT38': 'AUSTRALIA-PERU, Sochi, 26 June',
	'IMT39': 'NIGERIA-ARGENTINA, Saint Petersburg, 26 June',
	'IMT40': 'ICELAND-CROATIA, Rostov-on-Don, 26 June',
	'IMT41': 'SERBIA-BRAZIL, Moscow, 27 June',
	'IMT42': 'SWITZERLAND-COSTA RICA, Nizhny Novgorod, 27 June',
	'IMT43': 'KOREA REPUBLIC-GERMANY, Kazan, 27 June',
	'IMT44': 'MEXICO-SWEDEN, Ekaterinburg, 27 June',
	'IMT45': 'ENGLAND-BELGIUM, Kaliningrad, 28 June',
	'IMT46': 'PANAMA-TUNISIA, Saransk, 28 June',
	'IMT47': 'JAPAN-POLAND, Volgograd, 28 June',
	'IMT48': 'SENEGAL-COLOMBIA, Samara, 28 June',
	'IMT49': '1/8 final, A1-B2, Sochi, 30 JUNE',
	'IMT50': '1/8 final, C1-D2, Kazan, 30 JUNE',
	'IMT51': '1/8 final, B1-A2, Moscow, 1 JULY',
	'IMT52': '1/8 final, D1-C2, Nizhny Novgorod, 1 JULY',
	'IMT53': '1/8 final, E1-F2, Samara, 2 JULY',
	'IMT54': '1/8 final, G1-H2, Rostov-on-Don, 2 JULY',
	'IMT55': '1/8 final, F1-E2, Saint Petersburg, 3 JULY',
	'IMT56': '1/8 final, H1-G2, Moscow, 3 JULY',
	'IMT57': '1/4 final, W49-W50, Nizhny Novgorod, 6 JULY',
	'IMT58': '1/4 final, W53-W54, Kazan, 6 JULY',
	'IMT59': '1/4 final, W51-W52, Sochi, 7 JULY',
	'IMT60': '1/4 final, W55-W56, Samara, 7 JULY',
	'IMT61': '1/2 final, W57-W58, Saint Petersburg, 10 JULY',
	'IMT62': '1/2 final, W59-W60, Moscow, 11 JULY',
	'IMT63': 'Third place playoff, Saint Petersburg, 14 JULY',
	'IMT64': 'Final, Moscow, 15 JULY'

};